version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: annanorri992
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-zmY3cdivliOZjnKq}

  app:
    ports:
      - '5000:5000'
    environment:
      MONGO: mongodb://annanorri992:${MONGO_PASSWORD:-zmY3cdivliOZjnKq}@mongo:27017/
    build:
      context: .
      args:
        - NODE_ENV_ARG=${NODE_ENV_COMPOSE:-development}
    env_file:
      - /env/.env.${NODE_ENV_COMPOSE:-development}
    depends_on:
      - mongo

volumes:
  mongo-data:
# docker-compose build --build-arg NODE_ENV_COMPOSE=development app --build-arg MONGO_PASSWORD=password app --build-arg MONGO_PASSWORD=password mongo